In [1]:
#library we need

import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
#we need to remove the NaN value
#find out the median bedrooms

df.bedrooms.median()

4.0

In [4]:
#replaced
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis = 'columns'), df.price)

LinearRegression()

In [6]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [7]:
reg.intercept_

221323.00186540443

In [8]:
#find out the price with 3000 sqr ft area, 3 bedrooms and 40 years old
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [9]:
#Find the price with 2500 sqr ft area, 4 bedrooms, and 5 years old
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [10]:
#try to predict for the given csv file data
area_df = pd.read_csv('homeprices_prediction.csv')
area_df

area  bedrooms  age
0  1600         1   15
1  3500         5   10
2  2800         2   18
3  4000         7   15
4  4800         4    9
5  1100         3   14

In [11]:
p = reg.predict(area_df)
p

array([375536.02042126, 698168.76996624, 523704.67710387, 784819.16155002,
       823692.78232171, 369514.27751471])

In [12]:
area_df['prices']=p
area_df

area  bedrooms  age         prices
0  1600         1   15  375536.020421
1  3500         5   10  698168.769966
2  2800         2   18  523704.677104
3  4000         7   15  784819.161550
4  4800         4    9  823692.782322
5  1100         3   14  369514.277515

In [13]:
#save as a csv file
area_df.to_csv('predicted_prices.csv')